YEAR = 2018
SCRAPING_DATES = "scraping_dates"
COMMON_IDS = "common_ids"
CALENDARS = "calendars_2018"
REVIEWS_SQLITE = "reviews_2018-12"
REVIEWS_MYSQL = "reviews_2018"
AIRBNB = "airbnb_2018"
LINKS_BOOKING_SQLITE = "links"
BOOKING_COMMENTS="booking_comments"